# src/main/resources/application-dev.yml

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=TrainingDB;encrypt=true;trustServerCertificate=true
    username: AdminUser
    password: P@ssword
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      pool-name: TrainingPool-Hikari-Dev
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

logging:
  level:
    org.hibernate.SQL: DEBUG